# Generated by Django 2.2.16 on 2020-11-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_indexad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='foods_num',
            new_name='goods_num',
        ),
    ]
